package by.myProject.controller.command;

public enum AllCommands {
	REGISTR,
	SIGN_IN,
	SHOW_ALL_USERS,
	ADD_USER,
	REMOVE_USER,
	AUTHORIZE_USER,
	DO_AVALIABLE_USER,
	DO_REMOVE_USER,
	EXIT,
	ADD_NEW_WORKER,
	SHOW_ALL_BASE,
	REMOVE_WORKER,
	CHANGE_DATA,
	DO_REMOVE_WORKER;
}
